version: "3"

services:
  plone:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./jazkarta/shop:/app/lib/python3.8/site-packages/jazkarta/shop
    environment:
      SITE: Plone
      TYPE: classic
      DEBUG_MODE: "on"
      ZEO_ADDRESS: zeo:8100
      PROFILES: "jazkarta.shop:default"
    depends_on:
      - zeo

  zeo:
    image: plone/plone-zeo:latest
    restart: always
    volumes:
      - data:/data
    ports:
    - "8100"
  # The `dummy` service is here to make sure `docker-compose up` exits only when
  # `plone`'s health is `healthy`.
  dummy:
    image: busybox
    depends_on:
      plone:
        condition: service_healthy

volumes:
  data: {}