version: "3"

services:
  plone:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/jazkarta.shop
    environment:
      SITE: Plone
      TYPE: classic
      # This is not working on Github Actions. It works locally
      # Commenting out for now
      # PROFILES: "jazkarta.shop:default"

  # The `dummy` service is here to make sure `docker-compose up` exits only when
  # `plone`'s health is `healthy`.
  dummy:
    image: busybox
    depends_on:
      plone:
        condition: service_healthy
