name: Test

on:
  - push

jobs:
  test:
    name: Run e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build jazkarta.shop docker image
        run: docker-compose build
      - name: Start Plone server
        run: docker-compose up -d
      - name: Make sure the server container is running
        run: |
          # If we find the string `plone_1` in the output of `docker-compose ps`
          # and on the same line the word `healthy`, it means that the container is running. 
          docker-compose ps|grep plone_1.*healthy
      - name: Wait until the server is running
        run: |
          # Port 8080 is open. The Plone server might still be starting. We need to wait until
          # it's ready to serve requests. We try four times.
          curl --retry-connrefused --retry-max-time 40 --retry 5 --fail -v http://localhost:8080/ ||
          (sleep 3 &&
          curl --retry-connrefused --retry-max-time 40 --retry 5 --fail -v http://localhost:8080/) ||
          (sleep 3 &&
          curl --retry-connrefused --retry-max-time 40 --retry 5 --fail -v http://localhost:8080/) ||
          (sleep 3 &&
          curl --retry-connrefused --retry-max-time 40 --retry 5 --fail -v http://localhost:8080/)
      - name: Check that jazkarta.shop was installed
        if: ${{false}}  # The `PROFILES` environment variable is not working
        run: curl --fail -v http://localhost:8080/Plone/review-cart
      - name: Print plone server logs
        if: always()  # This step should be also run when a previous step failed
        run: docker-compose logs plone
