name: Test

on:
  - push

jobs:
  test:
    name: Run e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build jazkarta.shop docker image
        run: docker build . -t jazkarta.shop
        env:
           DOCKER_BUILDKIT: "1"

      - name: Start Plone server
        run: docker compose up -d
        env:
           DOCKER_BUILDKIT: "1"

      - name: Check that jazkarta.shop was installed
        run: curl --fail -v http://localhost:8080/Plone/review-cart

      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v6
        with:
          browser: chrome

      - name: Print plone server logs
        if: always()  # This step should be also run when a previous step failed
        run: docker compose logs plone
